version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "password"
      PGPASSWORD: "password"
    ports:
      - 5555:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - postgres:postgres
    depends_on:
      - postgres